name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mysql:
    name: PHP Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        database: ["mysql:latest"]
    services:
      database:
        image: docker.io/library/${{ matrix.database }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      APP_ENV: testing
      APP_DEBUG: true
      APP_KEY: "base64:6vTc4anmVbfttupxWi0WBwt5cVynmZm7CQBcSYGOsA0="
      APP_URL: http://localhost/
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: laravel
      DB_USERNAME: root
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Get cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, cli, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: 🛠️ Artisan Tasks
        run: |
          php artisan migrate
          php artisan storage:link
        env:
          DB_PORT: ${{ job.services.database.ports['3306'] }}

      - name: 🧫 Pest - Unit & Feature Tests
        run: composer test
        env:
          DB_PORT: ${{ job.services.database.ports['3306'] }}
